version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SUBDOMAIN=StevanusFirman
    container_name: backend_service
    volumes:
      - ./backend/db:/app/backend/db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=production
      - SUBDOMAIN=StevanusFirman
    container_name: frontend_service
